name: Angular CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      working-directory: ./client
      run: |
        npm ci
      env:
        CI: true
    - name: check tests
      working-directory: ./client
      run: |
        npm run test
      env:
        CI: true
    - name: check lint
      working-directory: ./client
      run: |
        npm run lint
      env:
        CI: true
    - name: build --prod
      working-directory: ./client
      run: |
        ng build --prod
      env:
        CI: true
